from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities import (
    CommunicationHistory,
    Customer,
    RefreshToken,
    RepairHistory,
    Shop,
    ShopMembership,
    User,
    Vehicle,
    VoiceNote,
    WalkInVisit,
)


class ShopRepository(Protocol):
    async def get_by_id(self, shop_id: UUID) -> Shop | None: ...
    async def get_by_slug(self, slug: str) -> Shop | None: ...
    async def get_by_name(self, name: str) -> Shop | None: ...
    async def add(self, shop: Shop) -> Shop: ...
    async def update(self, shop: Shop) -> Shop: ...


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_phone(self, phone: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def add(self, user: User) -> User: ...
    async def update_profile(
        self,
        user_id: UUID,
        *,
        full_name: str,
        phone: str | None | object = ...,
        email: str | None | object = ...,
    ) -> User | None: ...
    async def update_password(self, user_id: UUID, *, password_hash: str) -> User | None: ...
    async def set_active(self, user_id: UUID, *, is_active: bool) -> User | None: ...
    async def update_account_type(self, user_id: UUID, *, account_type: str) -> User | None: ...
    async def get_notification_prefs(self, user_id: UUID) -> dict | None: ...
    async def set_notification_prefs(self, user_id: UUID, prefs: dict) -> dict | None: ...
    async def set_email_verified(self, user_id: UUID, verified: bool = True) -> None: ...
    async def set_phone_verified(self, user_id: UUID, verified: bool = True) -> None: ...
    async def set_mfa(
        self,
        user_id: UUID,
        *,
        secret: str | None,
        enabled: bool,
        backup_codes_json: str | None | object = ...,
    ) -> User | None: ...
    async def set_mfa_backup_codes(self, user_id: UUID, backup_codes_json: str | None) -> User | None: ...


class MembershipRepository(Protocol):
    async def get(self, shop_id: UUID, user_id: UUID) -> ShopMembership | None: ...
    async def add(self, membership: ShopMembership) -> ShopMembership: ...
    async def update(self, membership: ShopMembership) -> ShopMembership: ...
    async def delete(self, membership_id: UUID) -> bool: ...
    async def list_for_user(self, user_id: UUID) -> list[ShopMembership]: ...
    async def list_for_shop(self, shop_id: UUID) -> list[ShopMembership]: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token_id: UUID, revoked_at: datetime) -> bool: ...
    async def revoke_all_for_user(self, user_id: UUID, revoked_at: datetime) -> None: ...
    async def exists_for_user_shop(self, user_id: UUID, shop_id: UUID) -> bool: ...


class CustomerRepository(Protocol):
    async def add(self, customer: Customer) -> Customer: ...
    async def update(self, customer: Customer) -> Customer: ...
    async def delete(self, shop_id: UUID, customer_id: UUID) -> bool: ...
    async def list_by_shop(self, shop_id: UUID) -> list[Customer]: ...
    async def search(self, shop_id: UUID, query: str) -> list[Customer]: ...
    async def get_by_id(self, shop_id: UUID, customer_id: UUID) -> Customer | None: ...


class VehicleRepository(Protocol):
    async def add(self, vehicle: Vehicle) -> Vehicle: ...
    async def update(self, vehicle: Vehicle) -> Vehicle: ...
    async def delete(self, shop_id: UUID, vehicle_id: UUID) -> bool: ...
    async def get_by_id(self, shop_id: UUID, vehicle_id: UUID) -> Vehicle | None: ...
    async def list_by_customer(self, shop_id: UUID, customer_id: UUID) -> list[Vehicle]: ...
    async def list_by_shop(self, shop_id: UUID) -> list[Vehicle]: ...
    async def get_by_vin(self, shop_id: UUID, vin: str) -> Vehicle | None: ...
    async def get_by_license_plate(self, shop_id: UUID, plate: str) -> Vehicle | None: ...
    async def find_by_year_make_model(
        self, shop_id: UUID, year: int, make: str, model: str
    ) -> list[Vehicle]: ...
    async def has_walk_in_visits(self, shop_id: UUID, vehicle_id: UUID) -> bool: ...


class RepairHistoryRepository(Protocol):
    async def add(self, entry: RepairHistory) -> RepairHistory: ...
    async def list_by_vehicle(self, shop_id: UUID, vehicle_id: UUID) -> list[RepairHistory]: ...
    async def list_by_vehicle_ids(
        self, shop_id: UUID, vehicle_ids: list[UUID]
    ) -> list[RepairHistory]: ...
    async def latest_by_customer_for_shop(
        self, shop_id: UUID
    ) -> dict[UUID, RepairHistory]: ...
    async def delete(self, shop_id: UUID, vehicle_id: UUID, repair_id: UUID) -> bool: ...


class CommunicationHistoryRepository(Protocol):
    async def add(self, entry: CommunicationHistory) -> CommunicationHistory: ...
    async def list_by_customer(
        self, shop_id: UUID, customer_id: UUID
    ) -> list[CommunicationHistory]: ...


class WalkInVisitRepository(Protocol):
    async def add(self, visit: WalkInVisit) -> WalkInVisit: ...
    async def update(self, visit: WalkInVisit) -> WalkInVisit: ...
    async def get_by_id(self, shop_id: UUID, visit_id: UUID) -> WalkInVisit | None: ...
    async def list_by_shop(
        self, shop_id: UUID, status: str | None = None, arrived_after: datetime | None = None
    ) -> list[WalkInVisit]: ...


class VoiceNoteRepository(Protocol):
    async def add(self, note: VoiceNote) -> VoiceNote: ...
    async def update(self, note: VoiceNote) -> VoiceNote: ...
    async def get_by_id(self, shop_id: UUID, note_id: UUID) -> VoiceNote | None: ...
    async def list_by_shop(self, shop_id: UUID) -> list[VoiceNote]: ...


class UnitOfWork(Protocol):
    shops: ShopRepository
    users: UserRepository
    memberships: MembershipRepository
    refresh_tokens: RefreshTokenRepository
    customers: CustomerRepository
    vehicles: VehicleRepository
    repair_histories: RepairHistoryRepository
    communications: CommunicationHistoryRepository
    walk_ins: WalkInVisitRepository
    voice_notes: VoiceNoteRepository

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def bind_shop(self, shop_id: UUID) -> None: ...
